language: scala

scala:
- 2.13.5

before_install:
- export PATH=${PATH}:./vendor/bundle
- git fetch --tags

install:
- rvm use 2.6.0 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 4.2.0

script:
- sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck scalafmtSbtCheck headerCheck test:headerCheck test ci-release docs/publishMicrosite