name: ropes
baseurl: /ropes
description: Type-level String Formats
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.0+58-734a3220-SNAPSHOT
org: Howard Perrin
markdown: kramdown
