name: ropes
baseurl: /ropes
description: Type-level String Formats
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.0+77-a15b926c-SNAPSHOT
org: Howard Perrin
markdown: kramdown
