addSbtPlugin("com.geirsson"      % "sbt-scalafmt"    % "1.5.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header"      % "5.0.0")
addSbtPlugin("io.spray"          % "sbt-boilerplate" % "0.6.1")
addSbtPlugin("com.47deg"         % "sbt-microsites"  % "0.9.0")
addSbtPlugin("com.geirsson"      % "sbt-ci-release"  % "1.2.2")
