addSbtPlugin("com.geirsson"      % "sbt-scalafmt"    % "1.5.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header"      % "5.2.0")
addSbtPlugin("io.spray"          % "sbt-boilerplate" % "0.6.1")
addSbtPlugin("com.47deg"         % "sbt-microsites"  % "0.9.7")
addSbtPlugin("com.geirsson"      % "sbt-ci-release"  % "1.4.31")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"   % "1.6.0")
