name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v5
    - name: SBT Format Check, Header Check, Test
      run: sbt scalafmtCheck scalafmtSbtCheck headerCheck test:headerCheck test
